src/modules/common/components/modal/index.ts, src/modules/common/components/modal/interfaces/index.ts, src/modules/common/components/modal/modal.tsx, src/modules/common/components/modal/styles/_modal.scss, src/modules/common/components/modal/styles/index.scss, src/utils/styles/styles.scss
Created a UI Component for Modal views on forms.
=> Adds UI Component for Modal Views

src/modules/dashboard/screens/productCreation/productCreation.tsx
Fixed issue where selected sustainability certificates didn't display upload file options.
=> Certificate upload fix

.env
Updated environment parameter to use the Auth0 Bazar Account.
=> BNS-157: Move Auth0 account to Bazar Account

src/modules/common/components/inputFile/inputFile.tsx, src/modules/common/components/modal/styles/_modal.scss, src/modules/common/components/modalFile/styles/_modalFile.scss, src/modules/dashboard/screens/companyCreation/companyCreation.tsx, src/modules/dashboard/screens/companyCreation/styles/_companyCreation.scss
Update select input, Modal files and fixed left section.
=> BNS 206: Application responsive tuning

src/modules/common/components/modal/modal.tsx, src/modules/common/components/modal/styles/_modal.scss
Fixed display error with modal styles
=> BNS-214 Fix modal display error

src/modules/common/components/modalFile/modalFile.tsx, src/modules/common/components/modalFile/styles/_modalFile.scss, src/modules/common/components/profilePhoto/styles/_profilePhoto.scss
- Update modal and modalFile components.
- Update profilePhoto component, add media 992px viewport size.
=> Fix/bns 217: Modal settings

src/modules/common/components/card/card.tsx, src/modules/common/components/card/interfaces/index.ts, src/modules/common/components/card/styles/_card.scss, src/modules/dashboard/layouts/dashboardLayout/dashboardLayout.tsx, src/modules/dashboard/screens/productCreation/hooks/useProductCreation.ts, src/modules/dashboard/screens/productCreation/productCreation.tsx, src/modules/dashboard/screens/productCreation/providers/index.ts, src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/dashboard/screens/productList/productList.tsx, src/modules/dashboard/screens/productList/providers/index.ts
Added logic to product list page, and refactored Card component to work with props.
=> BNS-202 Product List logic

src/modules/common/components/modal/styles/_modal.scss, src/modules/common/components/profilePhoto/styles/_profilePhoto.scss, src/modules/dashboard/screens/companyCreation/companyCreation.tsx, src/modules/dashboard/screens/companyCreation/styles/_companyCreation.scss
Update text filed and update modal confirmation.
=> BNS-218: Adjustment of text fields Company

src/modules/auth/pages/login/validators/index.ts, src/modules/auth/pages/register/validators/index.ts
https://bazar-network.atlassian.net/browse/BNS-243
=> BNS-243: Changing email validation to support middle dots on emails

src/index.css, src/modules/auth/pages/forgotPassword/forgotPassword.tsx
https://bazar-network.atlassian.net/browse/BNS-226
=> BNS-226: Removing margin on paragraphs from bootstrap library

src/modules/common/providers/index.ts, src/modules/dashboard/layouts/dashboardLayout/dashboardLayout.tsx, src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/dashboard/screens/productList/productList.tsx, src/modules/dashboard/screens/productList/providers/index.ts
User data endpoint implemented, user's full name and avatar displayed in mobile view, avatar displayed in browser view's navbar, and fixed menu's product option url
=> User name in the menu bar

src/modules/auth/pages/verify/hooks/useVerify.ts, src/modules/common/components/card/card.tsx, src/modules/common/components/productIcon/index.tsx, src/modules/common/providers/index.ts, src/modules/dashboard/layouts/dashboardLayout/dashboardLayout.tsx, src/modules/dashboard/screens/productDetails/hooks/useProductDetails.ts, src/modules/dashboard/screens/productDetails/interfaces/index.ts, src/modules/dashboard/screens/productDetails/productDetails.tsx, src/modules/dashboard/screens/productDetails/providers/index.ts, src/modules/dashboard/screens/productDetails/styles/_productDetails.scss, src/modules/dashboard/screens/productDetails/validators/index.ts, src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/dashboard/screens/productList/productList.tsx
Added user to outlet context to use on all dashboard pages, added on click to cards, added functionality to product details and implemented edit availability on product details.
=> BNS-199 Adjust Seller flow with company

src/modules/common/components/profilePhoto/interfaces/index.ts, src/modules/common/components/profilePhoto/profilePhoto.tsx, src/modules/dashboard/layouts/dashboardLayout/dashboardLayout.tsx, src/modules/dashboard/screens/companyCreation/companyCreation.tsx, src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/dashboard/screens/productList/productList.tsx
Fixed user role in Company creation page.
=> BNS-259 Validate the role of the company creation form

src/modules/dashboard/screens/productList/productList.tsx
Showing first image of the product in the card preview.
=> BNS-272 No product image is shown when listing the product

package.json, src/modules/common/components/productIcon/index.tsx, src/modules/common/components/select/index.ts, src/modules/common/components/select/interfaces/index.ts, src/modules/common/components/select/select.tsx, src/modules/dashboard/screens/companyCreation/companyCreation.tsx, src/modules/dashboard/screens/companyCreation/hooks/useCompanyCreation.ts, src/modules/dashboard/screens/companyCreation/validators/index.ts, src/modules/dashboard/screens/productCreation/hooks/useProductCreation.ts, src/modules/dashboard/screens/productCreation/productCreation.tsx, src/modules/dashboard/screens/productCreation/validators/index.ts, src/modules/dashboard/screens/productDetailsBuyer/productDetailsBuyer.tsx
Added react-select to refactor Select component and all it's uses. Added icons to refactored select, and logic to the pages that use it.
=> BNS-254 List icons are missing from product

src/modules/common/components/productIcon/index.tsx, src/modules/common/components/select/interfaces/index.ts, src/modules/common/components/select/select.tsx, src/modules/dashboard/screens/productCreation/hooks/useProductCreation.ts, src/modules/dashboard/screens/productDetails/productDetails.tsx
Minimum order option icons added. Icon added to selection on the input.
=> BNS-243 List icons are missing from Minimum order

src/modules/common/providers/index.ts, src/modules/dashboard/screens/companyCreation/hooks/useCompanyCreation.ts
Added sorting to country and city lists to display them ordered by name.
=> BNS-290 Setting the country and city select

src/modules/dashboard/screens/productCreation/hooks/useProductCreation.ts, src/modules/dashboard/screens/userApprovals/hooks/useUserApprovals.ts, src/modules/dashboard/screens/userApprovals/interfaces/index.ts, src/modules/dashboard/screens/userApprovals/providers/index.ts, src/modules/dashboard/screens/userApprovals/styles/_userApprovals.scss, src/modules/dashboard/screens/userApprovals/userApprovals.tsx, src/shared/config/interceptor/index.ts
Added functionality to User admin page, fixed approval modal styles to fit the screen, added feature to close approve/decline modal on click
=> BNS-238 Admin Development

src/modules/dashboard/layouts/dashboardLayout/dashboardLayout.tsx, src/modules/dashboard/screens/companyCreation/companyCreation.tsx, src/modules/dashboard/screens/companyCreation/hooks/useCompanyCreation.ts, src/modules/dashboard/screens/productList/productList.tsx
Modified Menu to display options for the buyer, changed create product dialogs accordingly
=> BNS-198 Adjust buyer flow

src/modules/common/components/card/card.tsx, src/modules/common/components/card/interfaces/index.ts, src/modules/common/components/card/styles/_card.scss, src/modules/common/hooks/useProductList.ts, src/modules/dashboard/layouts/dashboardLayout/dashboardLayout.tsx, src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/dashboard/screens/productList/productList.tsx, src/modules/dashboard/screens/productList/utils/index.ts, src/modules/dashboard/screens/productListAdmin/productListAdmin.tsx, src/modules/dashboard/screens/wishlist/hooks/useWishlist.ts, src/modules/dashboard/screens/wishlist/index.ts, src/modules/dashboard/screens/wishlist/providers/index.ts, src/modules/dashboard/screens/wishlist/wishlist.tsx, src/routers/dashboard/index.tsx
Added heart icon to the cards on product list for buyer, implemented post wishlist and onclick on the icon
=> BNS-258 Functionality Wishlist

src/modules/dashboard/layouts/dashboardLayout/dashboardLayout.tsx
Added conditional to user approval menu option to be displayed only for admin users.
=> BNS-334 Disable user option from menu for sellers/buyer

src/modules/dashboard/layouts/dashboardLayout/dashboardLayout.tsx, src/modules/dashboard/screens/productDetails/productDetails.tsx, src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/dashboard/screens/productList/productList.tsx, src/modules/dashboard/screens/wishlist/hooks/useWishlist.ts, src/modules/dashboard/screens/wishlist/wishlist.tsx
Added product's owner avatar to product card in product list, product details and added product's company in product's details. Also added functinality to go back from details to the page the user was before.
=> BNS-335 Product list/wishlist/details fixes

package.json, src/modules/auth/pages/login/login.tsx, src/modules/common/components/card/card.tsx, src/modules/common/components/card/interfaces/index.ts, src/modules/common/components/card/styles/_card.scss, src/modules/common/components/productIcon/index.tsx, src/modules/common/components/select/select.tsx, src/modules/dashboard/layouts/dashboardLayout/dashboardLayout.tsx, src/modules/dashboard/screens/productCreation/productCreation.tsx, src/modules/dashboard/screens/productDetails/hooks/useProductDetails.ts, src/modules/dashboard/screens/productDetails/productDetails.tsx, src/modules/dashboard/screens/productDetails/providers/index.ts, src/modules/dashboard/screens/productDetailsBuyer/components/modalConfirmBlock/index.tsx, src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/dashboard/screens/productList/productList.tsx, src/modules/dashboard/screens/productList/providers/index.ts, src/modules/dashboard/screens/productList/utils/index.ts, src/modules/dashboard/screens/productListAdmin/productListAdmin.tsx, src/modules/dashboard/screens/userApprovals/hooks/useUserApprovals.ts, src/modules/dashboard/screens/userApprovals/userApprovals.tsx, src/modules/dashboard/screens/wishlist/hooks/useWishlist.ts, src/modules/dashboard/screens/wishlist/wishlist.tsx, src/modules/wallet/components/WalletConnectionBSC/index.tsx, src/root.tsx
Added new status 'approved' to products, implemented new product list api calls, fixed filtering by basic product, fixed multiple lint issues.
=> BNS-335 Product list settings (Front)

src/modules/common/components/card/card.tsx, src/modules/common/components/card/interfaces/index.ts, src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/dashboard/screens/productList/productList.tsx, src/modules/dashboard/screens/productList/providers/index.ts, src/modules/dashboard/screens/productList/utils/index.ts, src/modules/dashboard/screens/userApprovals/hooks/useUserApprovals.ts
Added publish option to product card, implemented offset on product list call, fixed public status tag
=> BNS-337Adjusting the view in the product list

src/modules/dashboard/screens/productDetails/components/modalConfirmBlock/index.tsx, src/modules/dashboard/screens/productDetails/productDetails.tsx, src/modules/dashboard/screens/productDetails/validators/index.ts, src/modules/dashboard/screens/productList/productList.tsx, src/modules/dashboard/screens/transactionStarted/transactionStarted.tsx, src/modules/dashboard/screens/wishlist/hooks/useWishlist.ts, src/modules/dashboard/screens/wishlist/providers/index.ts, src/modules/dashboard/screens/wishlist/wishlist.tsx
Wishlist filters implemented, fixed some seller/buyer bugs on productdetails/product list
=> BNS-354 Setting categories in the buyer's view (Wish List)

package.json, src/modules/dashboard/layouts/dashboardLayout/dashboardLayout.tsx, src/modules/dashboard/layouts/dashboardLayout/utils/index.ts, src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/dashboard/screens/productList/productList.tsx, src/modules/lisk_api/transaction/blockchain/getTransactionById.ts, src/modules/lisk_api/util/serializar.ts, src/modules/payment/hooks/usePriceFeedBSC.ts, src/modules/wallet/abi/BProductSale.json, src/modules/wallet/components/WalletConnectionBSC/index.tsx, src/modules/wallet/helper/addressHelper.ts, src/modules/wallet/helper/constantHelper.ts, src/modules/wallet/helper/contractHelpers.ts, src/modules/wallet/helper/getCreateSellOrderContract.ts, src/modules/wallet/types/index.d.ts, src/modules/wallet/util/binanceRpcProvider.ts, src/modules/wallet/util/getNodeUrl.ts
Added changes to send sell order transacction to Binance testnet.
=> BNS-340   Cuando se publique una orden de venta registrar la transacción en blockchain (Seller)

src/modules/dashboard/screens/productDetails/components/modalConfirmPurchase/index.tsx
Fixed formatter and undefined type.
=> BNS-349 Fix productList props to Card component

package.json, src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/lisk_api/providers/index.ts, src/modules/lisk_api/types/registerOrderAssetType.ts, src/modules/wallet/abi/BProductSale.json, src/modules/wallet/helper/constantHelper.ts
- Adjusted contract number to use the new one.
- Included fresh abi changes of contrat to use trading fee of saller.
- Added endpoint client for getting data of wallet of bazar blockchain.
- Added orderId as uuid to be send to bazar blockchain.
- Disabled temp code to call bazar blockchain.
=> BNS-340 : Cuando se publique una orden de venta registrar la transacción en blockchain (Seller)

src/modules/dashboard/screens/productDetails/hooks/useProductDetails.ts
Added await sentence to execute the transaction.
=> BNS-329: Add buy with BNB

src/modules/dashboard/screens/productList/hooks/useProductList.ts
Added code to upload an image to IPFS and save the hash to bazar blockchain.
=> BNS-297: Validation Node IPFS

src/modules/dashboard/screens/productList/hooks/useProductList.ts, src/modules/lisk_api/transaction/seller/newFileAsset.ts
- Applied code changes to modify order of b64toBlob of program execution.
- Converted hash to string
- Increased transaction fee to 0.03 because of it is a transaction with new record and update of order.
=> BNS-297:  Validation Node IPFS
